
def build(bld):
    bld.program(
        use=['core', 'imguicore', 'imgui', 'opengl'],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        linkflags=[
            '-s', 'EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap"]',
            # '-s', 'DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1',
        ],
        target='vizgl',
    )
