
def build(bld):
    bld.stlib(
        use=['glm', 'api', 'geometryapi'],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        target='plot'
    )
