
def build(bld):
    bld.stlib(
        use=['api', 'mappingapi', 'openglapi'],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        target='mapping'
    )
