
def build(bld):
    bld.stlib(
        use=['opengl', 'renderer', 'plot'],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        target='views'
    )
