
def build(bld):
    bld.stlib(
        use=['api', 'colormapapi', 'opengl'],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        target='colormap'
    )
