
def build(bld):
    bld.stlib(
        use=[
            'camera',
            'components',
            'geometryapi',
            'mappingapi',
            'modelapi',
            'opengl',
            'plot',
            'rendererapi',
            'shadersapi',
        ],
        source=bld.path.ant_glob('*.cpp'),
        includes=['.'],
        export_includes=['.'],
        target='renderer'
    )
